source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'

inhibit_all_warnings!

target :BRStyle do
	pod 'MAObjCRuntime', 			  '~> 0.0.1'
	pod 'RestKit/ObjectMapping',	  '~> 0.24'
	
	target :BRStyleTests do
		pod 'OCHamcrest',			  '~> 4.1'
		#pod 'OCMock',				  '~> 3.1'
	end
	
end

