source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'

inhibit_all_warnings!

target :BRStyle do
	target :BRStyleTests do
		pod 'OCHamcrest',			  '~> 4.1'
		#pod 'OCMock',				  '~> 3.1'
	end
	
end

